language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main
   